name: "Continuous Integration"

on:
  push:
  pull_request:

jobs:
  build:

    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '10.x'

      - name: Install dependencies
        run: yarn install

      - name: Linting
        run: yarn lint

      - name: Test
        uses: ianwalter/puppeteer@v2.0.0
        with:
          args: yarn test

      - name: Build
        run: yarn build
